--- 
base_url: "http://alexvollmer.com"
author_name: "Alex Vollmer"
author_email: "alex.vollmer@gmail.com"
output_dir: output
data_sources: 
- items_root: /
  layouts_root: /
  type: filesystem_combined
